### ISSUE TITLE
imx-cst: do_packagedata failing

### ISSUE THREAD

**Issue by kraj** [Freescale/meta-freescale#878] opened 2021-10-01 05:02 UTC
seems this is the failure
```
fatal: unable to access 'https://gitlab.apertis.org/pkg/imx-code-signing-tool.git/': server certificate verification failed. CAfile: none CRLfile: none
```
see

https://errors.yoctoproject.org/Errors/Details/609986/

**Comment by otavio** [comment] 2021-10-01 11:36
@tprrt, can you take a look?

**Comment by tprrt** [comment] 2021-10-11 17:01
Hi,

Have you seen any new occurrences?

I tried to reproduce this issue without success.
Moreover, the DST Root CA X3, has expired Sept. 30, 2021, causing quite a bit of trouble, which could explain this.

Best regards,
Thomas

**Comment by kraj** [comment] 2021-10-11 17:09
yes cert perhaps was the reason. We should still apply this patch since it pins to right branch

see
https://github.com/Freescale/meta-freescale/pull/881

**Comment by angolini** [comment] 2022-02-01 14:20
Closing as I think the issue is solved now

**Closed by angolini** 2022-02-01 14:20 UTC
