### ISSUE TITLE
dunfell: latest OE-Core Weston change crashes imx XWayland

### ISSUE THREAD

**Issue by denix0** [Freescale/meta-freescale#901] opened 2021-10-28 19:38 UTC
This change in OE-Core was backported to dunfell:
https://git.openembedded.org/openembedded-core/commit/?h=dunfell&id=4efdcc10906945765aa28324ce1badc59cda2976

Though, meta-freescale provides own copy of weston recipe, it now clashes with those changes and XWayland crashes after couple minutes complaining that it can't find some modules.

I tried syncing changes, but there appears too many customizations in imx weston recipe, so it didn't work and I ran out of time. Reverting the above commit in OE-Core locally works for now, but meta-freescale needs to update with latest OE-Core dunfell.

**Comment by thochstein** [comment] 2021-11-15 22:06
Sorry, I'm finally looking at this. When I try to run xterm from a console I get this:

`xterm: Xt error: Can't open display: %s`

The weston log shows this:

```
[21:58:21.363] xserver listening on display :0
[21:58:21.363] launching '/usr/libexec/weston-desktop-shell'
[22:00:05.667] Spawned Xwayland server, pid 850
[22:00:05.854] xserver crashing too fast: 256
```

The last two lines appear after trying to run xterm.

**Comment by thochstein** [comment] 2021-11-16 15:56
A colleague reports an issue with missing `xkbcomp`:

```
Disabling glamor and dri3 support, XWAYLAND_NO_GLAMOR is set
Failed to initialize glamor, falling back to sw
sh: line 1: /usr/bin/xkbcomp: No such file or directory
sh: line 1: /usr/bin/xkbcomp: No such file or directory
XKB: Failed to compile keymap
Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
(EE) 
Fatal server error:
(EE) Failed to activate virtual core keyboard: 2(EE) 
[16:22:09.049] xserver crashing too fast: 256
```

Installing `xkbcomp` fixed the issue for him.

It seems now that the variable `XSERVER_RRECOMMENDS` [1] is no longer used since `xserver-xorg` is no longer used [2].

[1] https://github.com/openembedded/openembedded-core/blob/honister/meta/recipes-graphics/xorg-xserver/xserver-xorg.inc#L75
[2] https://github.com/openembedded/openembedded-core/commit/e933962061ac3fa1c0c1069b8075a5f7645001c4

@denix0 can you see if adding the packages in `XSERVER_RRECOMMENDS` helps?

**Comment by denix0** [comment] 2021-11-18 17:55
@thochstein none of those changes are on dunfell

Please see in the first message the exact change in OE-Core on dunfell that I bisected to cause the issue with XWayland from meta-freescale.

**Comment by thochstein** [comment] 2021-11-18 23:12
@denix0 sorry about that, too many context shifts...

Does this look like the problem you ran into?

https://github.com/openembedded/openembedded-core/commit/aa829e27a0d3bda3ed943005c1622e71d38bb872

**Comment by thochstein** [comment] 2021-11-19 19:54
@denix0, sorry for my confusion, too much context switching and complexity...

I'll try myself to backport the backported patch to `weston_8.0.0.imx_bb`.

Can you be specific what is needed to see the error? Do I need to do anything? Or do I need to run an app? xterm good enough?

**Comment by thochstein** [comment] 2021-11-19 20:09
Another question, are you using `imx-gpu-viv` drivers? I've recently been made aware that the latest update of those drivers was built on `gatesgarth` and is incompatible with the `glibc` on `dunfell`.

**Comment by thochstein** [comment] 2021-11-19 22:34
For that matter, I guess I need the distro you're using as well. I'm using fsl-xwayland.

I'm not seeing XWayland crash. I am able to open and close an xterm. I am seeing the Weston desktop disappear, replaced with a screen of text:

```
could not load cursor 'dnd-move'
could not load cursor 'dnd-copy'
could not load cursor 'dnd-none'
could not load cursor 'dnd-move'
could not load cursor 'dnd-copy'
could not load cursor 'dnd-none'
could not load cursor 'dnd-move'
could not load cursor 'dnd-copy'
could not load cursor 'dnd-none'
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
```

At this point I have to reboot. I'm not sure if this is because I'm sharing my display with my computer (DP) and with my board (8MQ EVK HDMI). Perhaps the second time I switch to the HDMI of my board is when I see the desktop disappear.

**Comment by denix0** [comment] 2021-11-19 23:14
@thochstein sorry for the delay - hectic day today...

Sorry, I wasn't specific enough about the crash - yes, the Weston desktop disappears for me as well and I believe I saw similar messages on the screen. Since it's been a while since I looked at it closely, I don't remember all the details.

The distro is `fslc-xwayland` from meta-freescale-distro. I do believe `imx-gpu-viv` is used by default.

The platform is Variscite DART-MX8M-MINI `imx8mm-var-dart.conf` from this layer, that builds on top of meta-freescale:
https://github.com/varigit/meta-variscite-fslc/tree/dunfell

That layer adds machine configs and some customizations, but I even tried to BBMASK their `recipes-graphics/wayland/`

So, BBMASK didn't help. Trying to merge the original change from OE-Core [1] to `weston_8.0.0.imx.bb` also didn't help. Reverting just a single [1] commit did help - XWayland and Weston were working again reliably.

[1] https://git.openembedded.org/openembedded-core/commit/?h=dunfell&id=4efdcc10906945765aa28324ce1badc59cda2976

**Comment by thochstein** [comment] 2022-01-04 20:36
Well, I finally got back to this, and now I cannot reproduce the problem. @denix0 can you see if the problem is fixed for you?

**Comment by thochstein** [comment] 2022-01-04 20:46
Hmm, I tried this again today and can no longer reproduce the problem. @denix0, can you see if you still see the problem? @MaxKrummenacher, perhaps you no longer need to revert.

**Comment by denix0** [comment] 2022-01-11 00:45
> Hmm, I tried this again today and can no longer reproduce the problem. @denix0, can you see if you still see the problem? @MaxKrummenacher, perhaps you no longer need to revert.

nope, still broken for me

**Comment by denix0** [comment] 2022-01-13 21:53
@thochstein just to clarify - the Weston shell/desktop is not crashing, but getting terminated by systemd after couple minutes due to newly added notify facility timing out. The issue seems to be specific to nxp/imx variant of the weston recipe.

**Comment by thochstein** [comment] 2022-01-13 22:32
Right, I did remember that, but I didn't remember that it took long. About how long does it take? Maybe I didn't wait long enough?

**Comment by MaxKrummenacher** [comment] 2022-01-20 08:02
Assuming this gets merged to openembedded core the issue will likely be fixed:
https://lists.openembedded.org/g/openembedded-core/message/160745

**Comment by thochstein** [comment] 2022-01-29 17:10
The problematic backport is now reverted:
https://github.com/openembedded/openembedded-core/commit/dabd41819563ec63fc5bd5fd0f4af64230e58130

**Comment by angolini** [comment] 2022-01-31 17:32
Can we close this issue?

**Comment by denix0** [comment] 2022-02-01 00:31
> Can we close this issue?

fine with me

**Closed** 2022-02-01 12:30 UTC
